dataset:
  predict_path: ''
  prediction_path: ''
  batch_size: 16
  max_token: 512
  num_workers: 16
  debug: False
t5:
  model: 'google/flan-t5-base'
gpus: 1
max_length: 20
beam: 1
ckpt_path: '.ckpt'